name: chat_gpt_flutter
description: Integration of ChatGPT API using Flutter framework.
version: 1.0.15
repository: https://github.com/hrvojecukman/chat_gpt_flutter

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6


flutter:
