name: chat_gpt_flutter
description: Integration of OpenAI API using Flutter framework, ChatGPT and more
version: 1.0.16
repository: https://github.com/hrvojecukman/chat_gpt_flutter

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7


flutter:
